"""
Django settings for application project.
Generated by 'django-admin startproject' using Django 6.0.3.
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import environ
import os

env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, ''),
    DB_ENGINE=(str, 'django.db.backends.postgresql'),
    DB_NAME=(str, 'questions'),
    DB_USER=(str, 'admin'),
    DB_PASSWORD=(str, 'admin'),
    DB_HOST=(str, '127.0.0.1'),
    DB_PORT=(int, 5432),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_file = BASE_DIR / '.env.local'
if os.path.exists(env_file):
    environ.Env.read_env(env_file)
    
# Security
SECRET_KEY = env('SECRET_KEY', default='django-insecure-dummy-key-for-dev-12345')
DEBUG = env('DEBUG', default=True)
ALLOWED_HOSTS = env('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5'
]
INSTALLED_APPS += ['questions', 'core']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'questions' / 'templates',
            BASE_DIR / 'core' / 'templates',
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'questions.context_processors.sidebar_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]
LOGIN_REDIRECT_URL = '/'

# Internationalization
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'questions' / 'static',
    BASE_DIR / 'core' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django Debug Toolbar
if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.insert(1, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1', '::1']
    
# Centrifugo
CENTRIFUGE_URL = "http://127.0.0.1:8001/api"
CENTRIFUGE_HMAC_SECRET = "TxU6Y4oYdbdu009zAaNiBKrXv4-sJugHhSK9jE28nzfBpFgs3yPigzEkaqEYcKtDh1QIAjsSexA4zjPHrBcAbg"
CENTRIFUGE_API_KEY = "iNg95jdHAMwSOnFUJD2fHOh4_fSNwb9ikC3jddW346HXObDcpDWud1xe7RZcIA2OQjhKIoAoH2MwYwp54q26yQ"

# Caches
REDIS_HOST = '127.0.0.1'
REDIS_PORT = '6379'
REDIS_CACHE_DB = '1'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_CACHE_DB}",
        "TIMEOUT": 60 * 10,
    }
}

# Celery
CELERY_BROKER_URL = 'redis://localhost:6379/2'