# Generated by Django 6.0.3 on 2026-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_tag_is_active_alter_answerlike_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'is_correct')},
        ),
    ]
