# Generated by Django 6.0.3 on 2026-04-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profilemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileManager',
        ),
    ]
