# Generated by Django 6.0.3 on 2026-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_profilemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_count',
            field=models.IntegerField(default=0, verbose_name='Активность'),
        ),
    ]
