# Generated by Django 4.2.30 on 2026-05-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_id'),
        ('core', '0004_profile_activity_count'),
    ]

    operations = [
    ]
