# Generated by Django 4.2.30 on 2026-05-11 21:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_avatar_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_image_dummy.png', null=True, upload_to=core.models.Profile.get_avatar_path, verbose_name='Аватар'),
        ),
    ]
