upstream ask_apple_backend {
    server web:8000;
}

server {
    listen 80;
    server_name localhost;

    # Сжатие
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    # Раздача медиа
    location ^~ /media/ {
        alias /app/media/;
    }

    # Раздача статики по расширению
    location ~* \.(js|css|jpeg|jpg|png|gif|ico|html|woff|woff2|ttf|svg)$ {
        root /app/static;
        rewrite ^/static/(.*)$ /$1 break;
        expires 1h;
    }

    # Проксирование на Gunicorn
    location / {
        proxy_pass http://ask_apple_backend;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache ask_cache;
        proxy_cache_valid 200 302 10m;
        proxy_cache_valid 404 1m;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    }
}